nuxt.config.js
package.json
yarn.lock

deploy test

---

assets/styles/client/client.scss
assets/styles/client/common.scss
components/client/shared/SharedHeader.vue
components/client/shared/SharedSidebar.vue
layouts/client.vue
pages/index.vue

Issues:
https://github.com/KienVu1504/SuperCook_FE/issues/17
https://github.com/KienVu1504/SuperCook_FE/issues/11
Change:
- add sidebar header
- add toggle btn for sidebar

add sidebar header

---

assets/styles/client/client.scss
assets/styles/client/common.scss
components/client/shared/SharedSidebar.vue

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/19
add sidebar close btn

add sidebar close btn

---

components/client/IngredientCategory.vue

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/15
add ingredient category

add ingredient category

---

assets/styles/client/client.scss
components/client/shared/SharedSidebar.vue
layouts/client.vue

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/8
add shared sidebar

add shared sidebar

---

components/client/RecipeItem.vue

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/14
Change:
- add recipe item

add recipe item

---

README.md
assets/styles/client/client.scss
components/client/IngredientCategory.vue
components/client/RecipeSidebar.vue
components/client/shared/SharedHeader.vue
components/client/shared/SharedSidebar.vue
layouts/client.vue
package.json
yarn.lock

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/24
Change:
- add recipe detail sidebar

add recipe detail sidebar

---

assets/styles/client/client.scss
components/client/RecipeSidebar.vue
layouts/client.vue
pages/index.vue

Issues: https://github.com/KienVu1504/SuperCook_FE/issues/23
Change:
- add main search content

add main search content

---

assets/styles/client/client.scss

*Issues:*
#29 
*Change*:
- fix main search result height

fix main search result height

---

components/client/IngredientCategory.vue
components/client/RecipeSidebar.vue
layouts/client.vue

*Issues:*
#28 
*Change*:
- fix Recipe detail sidebar not scrollable

fix Recipe detail sidebar not scrollable

---

assets/styles/client/common.scss

*Issues:*
#42 
*Change*:
add custom scrollbar

add custom scrollbar

---

components/client/IngredientCategory.vue
components/client/shared/SharedSidebar.vue
layouts/client.vue
nuxt.config.js
plugins/axios.js
plugins/vuex-persistedstate.js
store/admin/global.js
store/client/index.js
store/index.js

*Issues:*
#36 
*Change*:
- get sidebar data

get sidebar data

---

nuxt.config.js

*Issues:*
#53 
*Change*:
fix insecure request

hotfix insecure request

---

src/components/client/shared/SharedHeader.vue
src/components/client/shared/SharedSidebar.vue
src/views/Client.vue

*Issues:*
#30 
*Change*:
fix client responsive

fix client responsive

---

src/App.vue
src/assets/styles/client/client.scss
src/assets/styles/loader.scss
src/components/shared/Loader.vue
src/plugins/axios.js
src/store/index.js

*Issues:*
#45 
*Change*:
add loading gif

add loading gif

---

src/assets/styles/client/client.scss
src/components/client/shared/SharedSidebar.vue

*Issues:*
#60 
*Change*:
fix search bar overflow

fix search bar overflow

---

package.json
src/assets/styles/admin/admin.scss
src/components/admin/AdminLogin.vue
src/components/admin/ControlPanel.vue
src/router/index.js
src/store/modules/admin/global.js
src/views/Admin.vue
yarn.lock

*Issues:*
#78 
*Change*:
add admin login

add admin login

---

src/components/admin/AdminLogin.vue

*Issues:*
#84 
*Change*:
update password regex

update password regex

---

src/components/admin/AdminLogin.vue
src/components/admin/shared/Sidebar.vue
src/router/index.js

*Issues:*
#81 
*Change*:
add router guard for login

add router guard for login

---

package.json
src/App.vue
src/assets/styles/admin/admin.scss
src/assets/styles/admin/sideBar.scss
src/components/admin/ControlPanel.vue
src/components/admin/Dashboard.vue
src/components/admin/IngredientCategories.vue
src/components/admin/shared/Sidebar.vue
src/main.js
src/router/index.js
src/store/index.js
src/store/modules/admin/ingredientCategories.js
src/store/modules/admin/pagy.js
yarn.lock

*Issues:*
#83 
*Change*:
add ingredient categories manage page

add ingredient categories manage page

---

src/components/admin/AdminLogin.vue
src/components/admin/Ingredients.vue
src/components/admin/shared/Pagy.vue
src/router/index.js
src/store/index.js
src/store/modules/admin/global.js
src/store/modules/admin/ingredients.js

*Issues:*
#86 
*Change*:
add ingredients manage page

add ingredients manage page

---

src/components/client/IngredientCategory.vue
src/components/client/RecipeSidebar.vue
src/components/client/shared/SharedHeader.vue
src/components/client/shared/SharedSidebar.vue
src/store/modules/admin/pagy.js
src/store/modules/client/index.js
src/views/Client.vue

*Issues:*
#49 
*Change*:
add recipe search feature

add recipe search feature

---

src/components/client/RecipeItem.vue
src/components/client/shared/SharedHeader.vue
src/components/client/shared/SharedSidebar.vue
src/views/Client.vue

*Issues:*
#101 
*Change*:
Client SP UI

Client SP UI

---

src/components/client/shared/SharedSidebar.vue

*Issues:*
#96 
*Change*:
disable sidebar esc close

disable sidebar esc close

---

src/assets/styles/loader.scss

*Issues:*
#79 
*Change*:
fix loading animation color

loading animation color

---

src/components/admin/shared/Sidebar.vue
src/router/index.js
src/store/modules/admin/global.js
src/store/modules/admin/ingredientCategories.js
src/store/modules/admin/ingredients.js
src/store/modules/admin/recipes.js
src/store/modules/client/index.js

*Issues:*
#105 
*Change*:
update api validation

api validation

---

src/components/admin/Recipes.vue

*Issues:*
#105 
*Change*:
update recipe validator

update recipe validator

---

src/components/admin/Recipes.vue

*Issues:*
#109 
*Change*:
modal content input textarea type

modal content input textarea type

---

src/assets/styles/client/client.scss
src/views/Client.vue

*Issues:*
#63 
*Change*:
add selected ingredients list tagging

add selected ingredients list tagging

---

src/assets/styles/admin/admin.scss
src/views/Admin.vue

*Issues:*
#106 
*Change*:
fix admin background

fix admin background

---

src/components/admin/AdminLogin.vue
src/components/admin/IngredientCategories.vue
src/components/admin/Ingredients.vue
src/components/admin/Recipes.vue
src/components/client/shared/SharedHeader.vue

*Issues:*
#116 
*Change*:
End Sprint Recheck

End Sprint Recheck
